### ISSUE TITLE
Deprecate "get" and "function" syntax

### ISSUE THREAD

**Issue by lbguilherme** [sdkgen/sdkgen.github.io#3]
We can now declare sdkgen functions with `fn getSomething(a: int): Something`. But this can still be written as `get something(a: int): Something` or as `function getSomething(a: int): Something`. The last two should be deprecated.

A warning should be generated by the parser when they are used. But they should still work.

**Comment by pablohildo** [comment]
I suppose this issue asks for documentation for [this implementation](https://github.com/sdkgen/sdkgen/issues/3).
Is that right? If that's the case, I wanted to suggest a new component "DeprecationWarning".
I came up with something like this:
![image](https://user-images.githubusercontent.com/2402483/88130774-c69c3f80-cbb1-11ea-9a81-db5aff84f003.png)

I can work on this issue.
