### ISSUE TITLE
Implement optional arguments

### ISSUE THREAD

**Issue by dgadelha** [sdkgen/sdkgen.github.io#9]
Today, we have support for nullable arguments with the syntax `fn hello(name: string?)`

As now sdkgen passes arguments as objects, it is possible to implement optional arguments

A suggested syntax is: `fn hello(name?: string)`

**Why?** With nullable arguments, clients are forced to always send `null`. In a function with many nullable arguments, the amount of `null`'s would pollute the code.

**Comment by lbguilherme** [comment]
Maybe we should make any nullable argument to be optional. What do you think?
